language: node_js
node_js:
- '12'
branches:
  only:
  - develop
env:
  global:
  - secure: jmQ2w5rtTQIN63b+0puxVbkc50zNaFEnACa+h2PAJb/kfm+6SXJorUWyUt9YiLmT6fMpoiT13uhg/G7ufC6k8HGHIhssfv0imsmJxlE1pxgj9F4PcX27bs9Vz+6bh8jvQ4Yif5eV71jb/DqdnvWjtqz3V1L69Hpq2AirKCZZ3en3HNrToOtxaDxndm1XL56jTM4DWUtK4ITUvhoKCx6FdyookOU9rvkqOfWs2SSPUesDU0oAqQz2r2EB8cBYGcz10Gao19n9Yjh/UBPCzJkSrtFI3OhY9OxCUsLhntvbc0sefCOOkU54/m88uIhrr3GtQNtsrCBF39Ree43KZB+y6Tar+zNLUiegEaNNaPNwRsepXfLjXir5F8W133+sjCRg5LRTD4d5yqmaRwu8OxXVpU0vqLA9LQCDOxDTfCiyZCKm/JbkBQqKMnCk8p0F3H+mxV1B+1aKcmJuIFTHuTpxsyyxvY3pNQkUbQzXPgAm4G8tQ1nOSZl+rTE3/ZbZawAWza6aW9jT/tzoMcBdGtC7rODMBg1X/RS5zZmlLaZollLGQ8Ecx3CKZwzv4kV8tvtwk3F2irjN3VJbtehQgKfzm1Vp5azOQRTnabW413MW3OIBHCvXQIWyYFNkB9fNCVUULZh9pq0Zkt18uQ09Sts0ndgt+jmOX1WXkXOyvEWhYmo=
install:
- npm install
- echo $MONGODB_URI
before_script:
- npm run dev
deploy:
  provider: heroku
  api_key:
    secure: UPgJ4++JYX54JWwZLZuMG60DjJ2knKG9HxE8cYXhOralxVzYdO4bpsLH1p5t35euCKL1YMjiKaMStJgGXXgjXBWasc9MP/dau1TV0TSIbJL1Odj7pw7VLfTSSamtXTJ+mjD/mhV9bm6cagXGK/XhqMR6cx6N9umpDG3of8N05nxVQLoelCxxeWBKGW+dTCtWbHpxXnkUfAe+rl8QICnZKCwbC4K8f4/W6FnFtBD7p1i8bqtIqdYBlmkIS+LV10xJjc2jhGYDvTg51FvMJd0Qz7K2l3yczchUce9vqrANTUqd47fP6/bcFVNNMluuR6bNRqyUuJOtp7D7QENnIVupMOH05wY67GWM4rlw95SL8jYqyX9qhPgT65s0mQDNvRBSlOlSjh+UozwimRjH880L8EZDooXh32Ekjfy7BYTgbbqZw3URjcKn6hGB1NCo3j5iOWKK5nL+TewYrtu6i0fsWeZ+VyaBAsJ/9scJvWE2HUQ58fAWvQgWQzCxRF1YtrIAFw65usSraT1zfFRBGi67RlPAc6tsjOWMBv6SeUkAaBANfwUHAtMGhWiMY2cOyJHxYKTE8QFrIfJB2O7ugcf+xkQVGNXUxKciBsP8wpzTpasvdpw0TRBQJ0Osrxpvt/7NX5M0JPILRFEbFutyNXd+RBT6rxJZ6gvS53xI8bHQmb0=
  app: stufftracker
  strategy: git
notifications:
  slack:
    secure: hEixpqHDN5nB0NN2i17Y18n9uPXQsUfIpgofhkgUlRPrBdoL2jE9a/N4QAziVXJgfEeJH0jcys/MbX5K/tVhipnNCZkBVLK95Ba3hqNQJZuQmSRIEtNwzlEioDsPZ2U9AFokS4vbxV9Qu0rSUfBB5SBSzKjv1Q50tYWhdub+l4JsH7NRbu6mL+RSP99t29PgnHeYLgApuB0Ln2WyEBcFJAzOSJAU+mRUMaxgihTAmM77GRFYFnmU9Djei3pVqtij4Cw0LRFMYiTdKuMDu1KVdWa2GsLODS9WKIeV087moTCN6IQigUP6Knm1XA/r5r9d+95Wd+VjuaVQ4PHrl9hak+sPt66/IcSpdAh6lBUgTpuXA+2o2aHpnPsEyOG44066NQjoMlrw/lCWFjmGsBdPxkVpUtFFrazjeFTqm/h115zgjLAyRlkXhua3h/JaiVb3SbbkqMWBBUfGWWWlZDJp68mIE6DO5uvYXhDCaTXFXkQrF/8uYeNjIpIiE/hFZJpE3bSPuqzp8Ypmq7GhGC6LOgyG8s2+golsVzi6nwV+Mt8s6kfHQMRzAmVoleTJBm1oRel35wGG4G5/X/TYl6gCvb3+DmmjYEzcbDASUg/AjnV0yTqIP4X7GC62oQ0p9YahoDeD4cTPbyFthvIY7NJk0GS0rRAl50o1KvBUhe83W0M=
